openapi: 3.0.0
info:
  title: Image Moderation API
  version: 1.0.0
  description: API for moderating image content using AWS Rekognition

servers:
  - url: http://localhost:3000/api/v1
    description: Development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /images/moderate:
    post:
      summary: Moderate an image for inappropriate content
      security:
        - BearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Moderation results
          content:
            application/json:
              schema:
                type: object
                properties:
                  isInappropriate:
                    type: boolean
                  labels:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        confidence:
                          type: number
                        parentName:
                          type: string
                  timestamp:
                    type: string
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '500':
          description: Server error